export default {
    cNumber: 13,
    rNumber: 8,
    dataSource: [{
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 1,
        y: 1
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'lidatou001',
        name: '李大头',
        x: 1,
        y: 2
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdapang001',
        name: '王大胖',
        x: 2,
        y: 2
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangxiaopang001',
        name: '王小胖',
        x: 3,
        y: 2
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 4,
        y: 2
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 5,
        y: 2
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 6,
        y: 2
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 3,
        y: 3
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 3,
        y: 4
    }, {
        sex: 'M',
        isNew: 0,
        telephoneState: 0,
        umId: 'wangdatou001',
        name: '王大头',
        x: 3,
        y: 5
    }]
}
